feat: Add ability to add Version manually
Grohden/react-native-cli-bump-version pull request #3
Opened 2020-09-06 09:16 UTC by andreieuganox

**User Story**
As a developer I want to be able to define the Version manually.

**Background**
If for example you use CLI on CI level, you probably use Semantic Release (https://www.npmjs.com/package/semantic-release) to define the Versions of the Application. In this case, the versions created by react-native-cli-bump-version and Semantic Release will be different. To be able to use it with SR it will be good to add additional parameter to this CLI.

P.S. The changes were not tested tbh...sorry for that! 
P.S.S. Thank you for your work!

2020-09-06 16:14 UTC, Grohden commented
Thanks for the PR! I'm gona review it ASAP

2020-09-06 18:14 UTC, Grohden requested changes
You also need to change the root `react-native.config.js` to pass this new flag down

2020-09-06 18:14 UTC, Grohden commented on src/index.ts
> +    version: string
this would be `version?: string`

2020-09-06 18:14 UTC, Grohden commented on src/index.ts
> +        const next = incrementSemVer(current, version, type ?? 'minor')
no need to pass version to `incrementSemVer`, a
 ```typescript
const next = version ?? incrementSemVer(current, type ?? 'minor')
```
Would be better here

2020-09-06 19:41 UTC, andreieuganox reviewed
good to go

2020-09-06 19:41 UTC, andreieuganox commented on src/index.ts
> +    version: string
true...

2020-09-07 15:07 UTC, Grohden approved these changes

2020-09-07 15:09 UTC, merged

2020-09-07 15:09 UTC, Grohden commented
@andreieuganox again, thx for the PR, I'm gonna write tests and soon release it!

2020-09-07 15:36 UTC, Grohden commented
1.0.4 released, feel free to ask me anything in case something is wrong